Add top level disable and enable
agenda/agenda pull request #1109
Opened 2020-08-20 05:24 UTC by pdfowler

## Use Case
We have a job which sends out invites in a staged manner over a period of time: "sendInvites". Once enough people have responded to the invite, we don't want to send out any more invites. If someone later cancels, we want to continue sending out invites in a tiered manner.

## Current Implementation
We have adopted the pattern of querying any outstanding "sendInvites" jobs, and iterating over them and calling `job.disable()`. In the case where someone cancels, we do the same thing but call `job.enable()`

---
## Proposed Implementation
Following the example of `agenda.cancel()` and its relationship with `job.remove()`, this PR adds the following two methods:

> ### disable(mongodb-native query)
> 
> Disables any jobs matching the passed mongodb-native query, preventing any matching jobs from being run by the Job Processor.
> 
> ```js
> const numDisabled = await agenda.disable({name: 'externalServicePoller'});
> ```
> 
> Similar to `agenda.cancel()`, this functionality can be acheived with a combination of `agenda.jobs()` and `job.disable()`
> 
> ### enable(mongodb-native query)
> 
> Enables any jobs matching the passed mongodb-native query, allowing any matching jobs to be run by the Job Processor.
> 
> ```js
> const numEnabled = await agenda.enable({name: 'externalServicePoller'});
> ```
> 
> Similar to `agenda.cancel()`, this functionality can be acheived with a combination of `agenda.jobs()` and `job.enable()`

---

## PR Checks:

- [x] Add Test Coverage
- [x] Add documentation to README.md
- [ ] Update HTML documentation

2020-10-12 10:38 UTC, koresar requested changes
Code is good. Some code comments needs rewording though.

2020-10-12 10:38 UTC, koresar commented on lib/agenda/enable.js
> + * Enables any jobs matching the passed MongoDB query, and removes them from the database.
"and removes them from the database" ?
I don't see that happening in the code. :) Perhaps, the comment needs an update?

2020-10-12 10:38 UTC, koresar commented on lib/agenda/enable.js
> + * @caller client code, Agenda.purge(), Job.remove()
Is this comment correct? I don't see that in the PR changes.

2021-06-25 06:19 UTC, pdfowler commented
@koresar Thanks for the feedback and callouts on the comments/docs. I've updated my code with the upstream master and migrated my code to Typescript.

Only remaining task is the HTML docs, which I believe are handled as a part of the release process via the `docs` script. Let me know if there's anything else I can do on this PR

2021-08-04 02:47 UTC, koresar approved these changes

2021-08-04 02:48 UTC, merged

2021-08-04 02:49 UTC, koresar commented
Quality PR! Thanks for that.

2021-08-05 03:34 UTC, koresar commented
Published in v4.2.0.
Thanks for your contribution!