Optionally persist the result of a job
agenda/agenda pull request #1322
Opened 2021-05-24 10:04 UTC by ochrstn

Coming from BullMQ I was missing the ability to persist the job result.

I added the feature as an option that is disabled by default.

2021-07-20 09:30 UTC, ochrstn commented
I wanted to ask if this is going to be reviewed or how I should proceed with my merge request.

2021-08-01 06:11 UTC, harisvsulaiman commented
@ochrstn Sorry for the delay. Let me have a look at it

2021-08-01 06:18 UTC, harisvsulaiman commented on lib/agenda/create.ts
> +  const saveResult = this._definitions[name] ? this._definitions[name].saveResult || false : false
Renaming `saveResult` to `shouldSaveResult` will help conveying that its a boolean.

2021-08-01 11:03 UTC, harisvsulaiman approved these changes

2021-08-01 11:04 UTC, harisvsulaiman commented
@koresar can you review this too?

2021-08-04 11:31 UTC, koresar requested changes
Please document the new feature in the README.md

2021-08-09 11:03 UTC, harisvsulaiman commented
@ochrstn we would appreciate it if you could update the readme.md to document the new changes .
I'm hoping to get this into the agenda 5.0 release.

2021-08-13 21:09 UTC, ochrstn commented
> @ochrstn we would appreciate it if you could update the readme.md to document the new changes .
> I'm hoping to get this into the agenda 5.0 release.

> Please document the new feature in the README.md

Sorry for the late response. I will do it this weekend.

2021-08-14 08:23 UTC, harisvsulaiman commented
Looks good to me!

2021-08-14 08:48 UTC, harisvsulaiman commented
@ochrstn the checks are failing. You will have incorporate the latest master

2021-08-14 10:00 UTC, harisvsulaiman approved these changes

2021-08-14 10:01 UTC, merged

2021-08-14 10:02 UTC, harisvsulaiman commented
@ochrstn Thank you for your contribution. please join the agenda slack if you haven't joined already.

2021-08-19 09:25 UTC, GW00D commented
Hi, thanks for working on this, quite keen for this feature. Do we know which release this is targeted for and when that might be roughly?

2021-08-21 00:33 UTC, koresar commented
We don't know when. It depends on too many people.
But we hope to have this in the next major 5.0.

On Thu, 19 Aug 2021, 19:25 GW00D, ***@***.***> wrote:

> Hi, thanks for working on this, quite keen for this feature. Do we know
> which release this is targeted for and when that might be roughly?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/agenda/agenda/pull/1322#issuecomment-901756702>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAMMEL5PAWGOEOHYZT43STLT5TEY7ANCNFSM45M52NEA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-11-23 22:55 UTC, kubanac95 commented
Any news on this feature? Seeing it on master I thought it's part of 4.2.1, but looks like it has not aired yet

2022-03-01 12:02 UTC, JonLopezGarcia commented
I see that persisting the result of a job run would override the result of the previous job run. 
Is this the intended behavior ? What about persisting the result of each run ? What would be the best way to achieve this ?